server:
  port: 8089
#用于初始化AppProps类中阿里云的相关配置的  白名单
staffjoy:
  white-list-only: true
  white-list-phone-numbers: ${WHITE_LIST_PHONE_NUMBERS:18001112222}
  concurrency: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"