# application.yml

spring:
#使application-dev.yml文件生效
  profiles:
    active: dev
  application:
    name: company-service
#数据库配置
  datasource:
    url: ${COMPANY_DATASOURCE_URL}
    username: ${COMPANY_DATASOURCE_USERNAME}
    password: ${COMPANY_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate

staffjoy:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-servie:8080}
  bot-service-endpoint: ${BOT_SERVICE_ENDPOINT:http://bot-service:8080}